### ISSUE TITLE
C语言-数组指针相关问题

### ISSUE THREAD

**Issue by SUqerBrave** [gh0stkey/Binary-Learning#11]
#include<stdio.h>
int main()
{
int arr[] = {1,4,6,4,5,6,7,8,9,0};//为防止1+1=2，而不是arr[0+1]=2,故将这里arr[1]改为4
int(*px)[10] = &arr;
printf("%d %d \n",(*px)[0],px[0][0]);
printf("%d %d \n",(\*px+1)[0],px[0][0]);
printf("%d %d \n",(\*(px+1))[0],px[0][0]);

px++;
printf("%d %d \n",(*px)[0],px[0][0]);
}

打印结果为
1 1
4 1
1245120 1
1245120 1245120
Press any key to continue

px++; // 后 (*px)[0]就访问整个数组地址后的地址内的数据，此话有误需要大佬更正一下

实际情况需要的是(*px)++，但(*px)不能作为++的左值。正常情况还是使用循环(*px+i)[0]来遍历

**Comment by gh0stkey** [comment]
其实不用纠结这里，你要的是遍历元素，而实际上这里要了解的是数组指针的用法，在第二个例子中也给出了多维数组的例子。
