### ISSUE TITLE
var

### ISSUE THREAD

**Issue by wufake70** [gh0stkey/Binary-Learning#13]
![S40527-23372657.png](https://github.com/gh0stkey/Binary-Learning/assets/97246337/8c154168-55bf-4b4b-afc2-d4f5e76459a9)

这里的var应该是全局变量才符合结果

**Comment by gh0stkey** [comment]
好久没复习了，按我的理解这里就是段寄存器的属性探测，无论是全局变量还是局部变量，给过去的都是一个地址，论证的是CS段寄存器的属性不具备可写，所以这里`[]`内即便变成0x1也是一样可以达到探测属性的目的。
```
#include <stdio.h>

void main()
{
    __asm {
        MOV AX,CS
			MOV DS,AX
			MOV DWORD PTR DS:[1], eax
    }
	getchar();
}
```

**Comment by gh0stkey** [comment]
好久没复习了，按我的理解这里就是段寄存器的属性探测，无论是全局变量还是局部变量，给过去的都是一个地址，论证的是CS段寄存器的属性不具备可写，所以这里`[]`内即便变成0x1也是一样可以达到探测属性的目的。
```
#include <stdio.h>

void main()
{
    __asm {
        MOV AX,CS
	MOV DS,AX
	MOV DWORD PTR DS:[1], eax
    }
    getchar();
}
```
