### ISSUE TITLE
笔记中涉及的源码

### ISSUE THREAD

**Issue by An-ease** [gh0stkey/Binary-Learning#8]
博主的笔记似乎是语雀做的，pdf源代码复制的时候会带上行号，并且格式是乱的。

**Comment by gh0stkey** [comment]
有在线版本的，可以看一下：https://gh0st.cn/Binary-Learning/Binary-Learning.html
源码：https://github.com/gh0stkey/Binary-Learning/tree/gh-pages

**Comment by An-ease** [comment]
在线版本好像没有中级班的  不知道是不是没有更新完的缘故   而且中级的好像更新得很慢   anyway  感谢！！！

**Comment by gh0stkey** [comment]
:D 在线的笔记暂时没更新打算等中级班全部完成，更新的慢是因为我并不是全职在学习，有自己的工作内容，写完了就会更新～感谢关注～
